version: '3'
services:
  frontend:
    build: './RevengeOfNewsChallenger'
    ports: 
      - "5000:80"
    volumes:
      - ./Certificate/server.crt:/etc/ssl/certs/server.crt
  backend:
    build: './RevengeOfNewsChallengerBackEnd'
    ports:
      - "8080:80"
  tests:
    build: 'RevengeOfTheNewsChallenger.IntegrationTests'
