version: '3'
services:
  frontend:
    build: './RONCFrontEnd'
    ports: 
      - "5000:80"
    volumes:
      - ./RONCFrontEnd/Certificate/server.crt:/etc/ssl/certs/server.crt
  backend:
   build: './RONCBackEnd'
   ports:
     - "8080:80"
