#!/bin/bash

./Scripts/backEndBuildTest

if 
    [ $? = 0 ]; 
    then ./Scripts/frontEndBuildTest;
    else
        exit 1;
fi

if 
    [ $? = 0 ]; 
    then ./Scripts/dockerStartScript;
    else
        exit 1;
fi

if 
    [ $? = 0 ]; 
    then ./Scripts/integrationBuildTest;
    else
        exit 1;
fi
